"""Podium Coach server — in-memory event log, state for the presenter phone.

Implements docs/CONTRACT.md. One process on Reed's laptop, no database, no disk.
Frame bytes (`image_b64`) are dropped from the log and never written anywhere.
"""

from __future__ import annotations

import asyncio
import json
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from fastapi import FastAPI
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from dotenv import load_dotenv

import cues

REPO_ROOT = Path(__file__).resolve().parent.parent
CUES_PATH = REPO_ROOT / "config" / "cues.json"
STATIC = Path(__file__).resolve().parent / "static"

# override=True: an empty ANTHROPIC_API_KEY exported by a parent shell would
# otherwise win silently and send every cue down the fallback path.
load_dotenv(REPO_ROOT / ".env", override=True)

# Degradation rule from the contract: metrics go null after this long with no chunk.
METRICS_STALE_S = 30.0

def emit_cue(category: str, text: str, reason: str) -> None:
    """Route a server-generated cue through the same append path as posted events."""
    append_event(
        Event(
            type="cue",
            ts=datetime.now(timezone.utc).isoformat(),
            payload={"category": category, "text": text, "reason": reason},
        )
    )


@asynccontextmanager
async def lifespan(_app: FastAPI):
    """Start the cue loop with the server and cancel it on shutdown."""
    task = asyncio.create_task(cues.run_loop(build_state, load_cue_config, emit_cue))
    key = "present" if __import__("os").environ.get("ANTHROPIC_API_KEY") else "MISSING"
    print(f"[startup] cue loop running | ANTHROPIC_API_KEY {key}")
    yield
    task.cancel()


app = FastAPI(title="Podium Coach", lifespan=lifespan)


class Event(BaseModel):
    """One event as posted by any sender, or generated by the server itself."""

    type: str
    ts: str
    payload: dict[str, Any] = Field(default_factory=dict)


# In-memory only. Cleared by POST /reset, lost on restart. That is the design.
EVENTS: list[dict[str, Any]] = []
SESSION_START: datetime | None = None


def load_cue_config() -> dict[str, Any]:
    """Read config/cues.json fresh so Adam can tune thresholds without a restart."""
    try:
        return json.loads(CUES_PATH.read_text())
    except Exception as exc:  # a missing or half-written file must not kill the loop
        print(f"[warn] could not read {CUES_PATH}: {exc}")
        return {}


def parse_ts(ts: str) -> datetime:
    """Parse a sender's ISO 8601 timestamp, tolerating a trailing Z and naive times."""
    try:
        parsed = datetime.fromisoformat(ts.replace("Z", "+00:00"))
    except (ValueError, AttributeError):
        return datetime.now(timezone.utc)
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed


def append_event(event: Event) -> dict[str, Any]:
    """Append to the log, start the clock if needed, log one line. Frames are stripped."""
    global SESSION_START

    when = parse_ts(event.ts)
    payload = dict(event.payload)

    image_b64 = payload.pop("image_b64", None)
    record = {
        "type": event.type,
        "ts": event.ts,
        "at": when,
        "payload": payload,
    }
    EVENTS.append(record)

    # A real session_start always sets the clock, and corrects one started by a
    # stray event. Otherwise the first event of any kind starts it from SERVER
    # receipt time, not the sender's ts: a canned curl with a hardcoded stale
    # timestamp would otherwise start the talk in the past. Deliberate extension
    # of docs/CONTRACT.md.
    if event.type == "session_start":
        SESSION_START = when
    elif SESSION_START is None:
        SESSION_START = datetime.now(timezone.utc)

    detail = json.dumps(payload)[:160]
    if image_b64 is not None:
        detail = f"image_b64 {len(image_b64)} chars | {detail}"
    print(f"[{when.isoformat()}] {event.type}: {detail}")
    return record


def elapsed_s() -> float:
    """Seconds since session start, clamped at zero so the countdown never runs backwards."""
    if SESSION_START is None:
        return 0.0
    return max(0.0, (datetime.now(timezone.utc) - SESSION_START).total_seconds())


def latest_payload(event_type: str) -> dict[str, Any] | None:
    """Payload of the most recent event of this type, or None."""
    for record in reversed(EVENTS):
        if record["type"] == event_type:
            return record["payload"]
    return None


def outline_state(elapsed: float) -> tuple[str | None, float, int | None]:
    """Derive (current_section, section_over_by_s, planned_minutes) from the outline.

    With no slide detection the server cannot know which section the presenter is
    actually in, so the section is derived from the plan and drift is zero until the
    talk runs past the last section. A `slide_change` event carrying `outline_section`
    overrides that and gives real per-section drift.
    """
    start = latest_payload("session_start") or {}
    outline = start.get("outline") or []
    planned_minutes = start.get("planned_minutes")

    if not outline:
        return None, 0.0, planned_minutes

    # Cumulative planned end, in seconds, for each section.
    bounds: list[tuple[str, float, float]] = []
    running = 0.0
    for section in outline:
        title = str(section.get("title", ""))
        length = float(section.get("minutes", 0)) * 60.0
        bounds.append((title, running, running + length))
        running += length

    slide = latest_payload("slide_change") or {}
    actual = slide.get("outline_section")
    if actual:
        for title, _begin, end in bounds:
            if title == actual:
                return title, max(0.0, elapsed - end), planned_minutes

    for title, begin, end in bounds:
        if begin <= elapsed < end:
            return title, 0.0, planned_minutes

    last_title, _begin, last_end = bounds[-1]
    return last_title, max(0.0, elapsed - last_end), planned_minutes


def engagement_state() -> dict[str, Any]:
    """Latest audience score and the full series, for the recap and the cue loop."""
    series = [
        {
            "t": round(max(0.0, (r["at"] - SESSION_START).total_seconds()), 1)
            if SESSION_START
            else 0.0,
            "score": r["payload"].get("engagement"),
            "note": r["payload"].get("note"),
        }
        for r in EVENTS
        if r["type"] == "audience_score"
    ]
    latest = series[-1]["score"] if series else None
    return {"latest": latest, "series": series}


def metrics_state() -> dict[str, Any] | None:
    """Metrics from the most recent transcript_chunk, or None if the audio went quiet."""
    for record in reversed(EVENTS):
        if record["type"] != "transcript_chunk":
            continue
        age = (datetime.now(timezone.utc) - record["at"]).total_seconds()
        if age > METRICS_STALE_S:
            return None
        return record["payload"].get("metrics")
    return None


def cue_state() -> dict[str, Any] | None:
    """The last cue, while it is still within its display window. None otherwise."""
    config = load_cue_config()
    show_for = float(config.get("show_cue_for_s", 15))
    for record in reversed(EVENTS):
        if record["type"] != "cue":
            continue
        if (datetime.now(timezone.utc) - record["at"]).total_seconds() > show_for:
            return None
        return {
            "text": record["payload"].get("text"),
            "category": record["payload"].get("category"),
            "at": record["ts"],
        }
    return None


@app.post("/events")
async def post_event(event: Event) -> dict[str, bool]:
    """Accept an event from any sender. Always 200 so no sender ever crashes."""
    append_event(event)
    return {"ok": True}


@app.get("/events")
async def get_events(since: str | None = None) -> list[dict[str, Any]]:
    """The event log, minus frame bytes. The recap page calls this once at /end."""
    cutoff = parse_ts(since) if since else None
    return [
        {"type": r["type"], "ts": r["ts"], "payload": r["payload"]}
        for r in EVENTS
        if cutoff is None or r["at"] >= cutoff
    ]


def build_state() -> dict[str, Any]:
    """The /state payload. Shared by the HTTP route and the cue loop."""
    elapsed = elapsed_s()
    current_section, over_by, planned_minutes = outline_state(elapsed)
    remaining = (
        max(0.0, planned_minutes * 60.0 - elapsed) if planned_minutes is not None else None
    )
    return {
        "session": {
            "started_at": SESSION_START.isoformat() if SESSION_START else None,
            "planned_minutes": planned_minutes,
            "elapsed_s": round(elapsed, 1),
            "remaining_s": round(remaining, 1) if remaining is not None else None,
            "current_section": current_section,
            "section_over_by_s": round(over_by, 1),
        },
        "cue": cue_state(),
        "engagement": engagement_state(),
        "metrics": metrics_state(),
    }


@app.get("/state")
async def get_state() -> dict[str, Any]:
    """What the presenter page polls every 2 s."""
    return build_state()


@app.get("/health")
async def health() -> dict[str, Any]:
    """Fastest way to confirm the server is up over the tunnel without sending an event."""
    return {"ok": True, "events": len(EVENTS), "session_started": SESSION_START is not None}


@app.post("/reset")
async def reset() -> dict[str, Any]:
    """Clear state between rehearsals."""
    global SESSION_START
    EVENTS.clear()
    SESSION_START = None
    print("[reset] state cleared")
    return {"ok": True}


@app.get("/audience")
async def audience_page() -> FileResponse:
    """Camera page for the iPhone at the back of the room. See docs/AUDIENCE-PAGE.md."""
    return FileResponse(STATIC / "audience.html", media_type="text/html")


@app.get("/presenter")
async def presenter_page() -> FileResponse:
    """The podium phone: countdown, one cue, a thin engagement line. Nothing else."""
    return FileResponse(STATIC / "presenter.html", media_type="text/html")
